name: "example"
version: '1.0.0'
main: org.example.Main
api-version: "1.16"

commands:

  lock:
    description: "Locks the chest looked at"
    usage: "/<command> <true or false lock state>"
    aliases: []
